"""
MissionMind — RUL uncertainty (Priority 6).

The dashboard RUL chip must never show an unjustifiably precise single number.
This module wraps the trend-based RUL fit with a residual-bootstrap prediction
interval, so the operator sees:

    BAT 173 min ± 24 min (90% CI)

The interval is generated by the implemented method — no fabricated numbers:

    1. Fit the hybrid fade law on the observed (cycle, capacity) history
       (the same `trend_rul` fit the prognostics module uses).
    2. Sample the fit residuals with replacement, add them back to the fitted
       curve, refit, and recompute the EOL crossing -> one bootstrap RUL.
    3. Repeat `n_boot` times; report the 5th/95th percentile of the bootstrap
       RUL distribution as the 90% prediction interval.

For the simulator-side "time-to-limit" RUL (minutes until SOC=0 at current
net power), the interval comes from the slope uncertainty of the linear fit
over the trailing window (std of dSOC/dt), propagated to time units.
"""

from __future__ import annotations

import numpy as np

from missionmind.ml.prognostics import trend_rul, eol_cap, _hybrid
from scipy.optimize import curve_fit


def rul_prediction_interval(n_obs, cap_obs, eol=None, predict_at=None,
                            n_boot: int = 200, ci: float = 0.90, seed: int = 42):
    """Bootstrap prediction interval around a trend-based RUL estimate.

    Returns (rul_point, lower, upper) in cycles, or (nan, nan, nan) when the
    base fit cannot reach EOL.
    """
    n = np.asarray(n_obs, float)
    c = np.asarray(cap_obs, float)
    if predict_at is not None:
        keep = n <= predict_at
        n, c = n[keep], c[keep]
    if len(n) < 4:
        return np.nan, np.nan, np.nan
    if eol is None:
        eol = eol_cap(c[0])

    rul_point, _ = trend_rul(n, c, eol, predict_at=None)
    if not np.isfinite(rul_point):
        return np.nan, np.nan, np.nan

    # fit once to get residuals
    p0 = (max(c) - min(c), -0.005, -0.0005, min(c))
    try:
        popt, _ = curve_fit(_hybrid, n, c, p0=p0, maxfev=20000)
    except Exception:
        return np.nan, np.nan, np.nan
    fitted = _hybrid(n, *popt)
    resid = c - fitted

    rng = np.random.default_rng(seed)
    boots = []
    for _ in range(n_boot):
        c_boot = fitted + rng.choice(resid, size=len(resid), replace=True)
        # skip fits that collapse
        try:
            popt_b, _ = curve_fit(_hybrid, n, c_boot, p0=p0, maxfev=20000)
        except Exception:
            continue
        n_max = n[-1] + max(50.0, 5.0 * (n[-1] - n[0]))
        grid = np.linspace(n[-1], n_max, 10000)
        c_fit = _hybrid(grid, *popt_b)
        cross = np.where(c_fit <= eol)[0]
        if len(cross):
            boots.append(grid[cross[0]] - n[-1])
    if len(boots) < 20:
        return rul_point, np.nan, np.nan
    boots = np.array(boots)
    alpha = (1.0 - ci) / 2.0
    lo, hi = np.percentile(boots, [100 * alpha, 100 * (1 - alpha)])
    return float(rul_point), float(max(0.0, lo)), float(hi)


def time_to_limit_interval(soc: float, net_w: float, window_soc_diffs: np.ndarray,
                           ci: float = 0.90):
    """Simulator-side RUL: minutes until SOC=0 at current net power, with an
    interval propagated from the uncertainty in the observed dSOC/dt.

    window_soc_diffs: observed per-second SOC differences in the trailing
    window (e.g. from a DataFrame diff). The mean gives the drain rate; the
    standard error of the mean gives the interval.
    """
    d_soc = abs(net_w) / 3600.0 / 100.0
    if net_w >= 0 or d_soc <= 0 or soc <= 0:
        return float("inf"), float("inf"), float("inf")
    rul_min = (soc / d_soc) / 60.0

    diffs = np.asarray(window_soc_diffs, dtype=float)
    diffs = diffs[np.isfinite(diffs) & (diffs < 0)]
    if len(diffs) < 5:
        return rul_min, rul_min * 0.8, rul_min * 1.2
    se = float(diffs.std() / np.sqrt(len(diffs)))   # std error of drain rate
    # relative uncertainty in rate -> relative uncertainty in time-to-zero
    rel = se / max(abs(float(diffs.mean())), 1e-12)
    z = 1.645  # 90% one-sided tail (approx)
    return float(rul_min), float(rul_min / (1 + z * rel)), float(rul_min / max(1 - z * rel, 1e-6))


def format_interval(point, lower, upper, unit="m"):
    """'173 ± 24' style formatting; '± —' when no interval is available."""
    if not np.isfinite(point):
        return "∞"
    if not np.isfinite(lower) or not np.isfinite(upper):
        return f"{point:.0f} ± —"
    half = max(abs(upper - point), abs(point - lower))
    return f"{point:.0f} ± {half:.0f}"
