"""Shared pytest fixtures for the MissionMind test suite.

The suite's CSV-dependent tests read the three scenario telemetry files
(run_normal.csv, run_solar_failure.csv, run_radiator_failure.csv). Those
files are gitignored by design (regenerable via
`python -m missionmind.simulator.run_scenarios`), so a fresh checkout does
not contain them. This module:

  * regenerates ALL THREE CSVs (a consistent set from the CURRENT simulator)
    when ANY of them is missing — never a partial mix of simulator versions;
  * records the generator signature in data/scenario_manifest.json;
  * WARNs (and does NOT touch) when CSVs exist but were generated by a
    different simulator version, so stale physics is detectable instead of
    silently replaying into the tests.

Generation is fast (~0.3 s per scenario) and writes only to gitignored
paths, so the repo's phantom-diff guard stays clean.
"""

import os
import sys

TESTS_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(TESTS_DIR, "..", ".."))
if ROOT not in sys.path:
    sys.path.insert(0, ROOT)

DATA_DIR = os.path.join(ROOT, "missionmind", "data")


def _generate_scenario_csvs() -> None:
    """Regenerate the full scenario set (all three, current simulator)."""
    from missionmind.simulator.run_scenarios import (
        run_scenario, write_scenario_manifest, SCENARIOS,
    )

    n_rows = {}
    for mode, fname in SCENARIOS.items():
        path = os.path.join(DATA_DIR, fname)
        df = run_scenario(failure_mode=mode, duration_s=3600)
        df.to_csv(path, index=False)
        n_rows[fname] = len(df)
    write_scenario_manifest(n_rows, add_noise=False, duration_s=3600)


def pytest_sessionstart(session) -> None:
    from missionmind.simulator.run_scenarios import check_stale_scenarios

    missing = [f for f in ("run_normal.csv", "run_solar_failure.csv",
                           "run_radiator_failure.csv")
               if not os.path.exists(os.path.join(DATA_DIR, f))]
    if missing:
        print(f"[conftest] regenerating missing scenario CSVs: {missing}")
        _generate_scenario_csvs()
        return

    stale = check_stale_scenarios()
    if stale:
        # Never regenerate silently: the CSV set on disk was produced by a
        # different simulator version (physics change). Regenerate it
        # deliberately with: python -m missionmind.simulator.run_scenarios
        print(f"[conftest] WARNING: stale scenario CSVs from an older "
              f"simulator version: {stale}. Regenerate deliberately with "
              f"`python -m missionmind.simulator.run_scenarios`.")
